application:
  name: familie-ba-e2e
server:
  servlet:
    context-path: /
  port: 8092

no.nav.security.jwt:
  client:
    registration:
      familie-ba-sak:
        resource-url: ${FAMILIE_BA_SAK_API_URL}
        token-endpoint-url: http://localhost:1111/v2.0/token
        grant-type: client_credentials
        scope: ${FAMILIE_BA_SAK_SCOPE}
        authentication:
          client-id: ${BA_SAK_CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-ba-mottak:
        resource-url: ${FAMILIE_BA_MOTTAK_API_URL}
        token-endpoint-url: http://localhost:1111/v2.0/token
        grant-type: client_credentials
        scope: ${FAMILIE_BA_MOTTAK_SCOPE}
        authentication:
          client-id: ${BA_SAK_CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic

KAFKA_BROKERS: localhost:9092
FAMILIE_BA_SAK_API_URL: http://localhost:8089
FAMILIE_BA_SAK_SCOPE: api://146ccc69-7cd0-4b8e-86a5-144534e53a00/.default
FAMILIE_BA_MOTTAK_API_URL: http://localhost:8090
FAMILIE_BA_MOTTAK_SCOPE: api://288f2ef5-23fa-4fc5-af6b-6001adaf9e50/.default


logging:
  level:
    root: INFO