
spring:
  kafka:
    jaas:
      enabled: false
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      security:
        protocol: SASL_PLAINTEXT
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='igroup' password='itest';
      schema.registry.url: http://localhost:8081
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer


KAFKA_BROKERS: localhost:9092

logging:
  level:
    root: INFO