package no.nav.ba.e2e.familie_ba_sak.domene

enum class StegType {
    REGISTRERE_SØKNAD,
    REGISTRERE_PERSONGRUNNLAG,
    VILKÅRSVURDERING,
    SEND_TIL_BESLUTTER,
    BESLUTTE_VEDTAK,
    IVERKSETT_MOT_OPPDRAG,
    VENTE_PÅ_STATUS_FRA_ØKONOMI,
    JOURNALFØR_VEDTAKSBREV,
    DISTRIBUER_VEDTAKSBREV,
    FERDIGSTILLE_BEHANDLING,
    BEHANDLING_AVSLUTTET
}