version: "3"
services:
  mq:
    image: ibmcom/mq
    ports:
      - "1414:1414"
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
  familie-mock-server:
    image: docker.pkg.github.com/navikt/familie-mock-server
    ports:
      - 1337:1337
  # For Azure
  mock-oauth2-server:
    image: docker.pkg.github.com/navikt/mock-oauth2-server/mock-oauth2-server:0.1.33
    ports:
      - 1111:1111
  # For STS
  nav-auth-mock:
    image: docker.pkg.github.com/navikt/nav-auth-mock/nav-auth-mock
    ports:
      - 8200:8200
  postgres-sak:
    image: postgres:11
    environment:
      POSTGRES_USER: familie
      POSTGRES_DB: familiebasak
      POSTGRES_PASSWORD: familie-pwd
    ports:
      - 5432:5432
  #postgres-mottak:
  #  image: postgres:11
  #  environment:
  #    POSTGRES_USER: familie
  #    POSTGRES_DB: familiebamottak
  #   POSTGRES_PASSWORD: familie-pwd
  #  ports:
  #    - 5439:5432
  postgres-oppdrag:
    image: postgres:11
    environment:
      POSTGRES_USER: familie
      POSTGRES_DB: familieoppdrag
      POSTGRES_PASSWORD: familie-pwd
    ports:
      - 5433:5432
  #familie-ba-mottak:
  #  restart: always
  #  image: docker.pkg.github.com/navikt/familie-ba-mottak/familie-ba-mottak:latest
  #  environment:
  #    SPRING_PROFILES_ACTIVE: e2e
  #    MOTTAK_CLIENT_ID: ${MOTTAK_CLIENT_ID}
  #    MOTTAK_FRONTEND_CLIENT_ID: ${MOTTAK_FRONTEND_CLIENT_ID}
  #    MOTTAK_CLIENT_SECRET: ${MOTTAK_CLIENT_SECRET}
  #    MOTTAK_BA_SAK_SCOPE: ${BA_SAK_SCOPE}
  #    MOTTAK_FAMILIE_INTEGRASJONER_SCOPE: ${INTEGRASJONER_SCOPE}
  #    JOURNALFOERINGHENDELSE_V1_TOPIC_URL: aapen-dok-journalfoering-v1-e2e
  familie-ba-sak:
    restart: always
    image: af93f7368489 #docker.pkg.github.com/navikt/familie-ba-sak/familie-ba-sak:latest
    depends_on:
      - postgres-sak
      - mock-oauth2-server
      - familie-integrasjoner
      - familie-oppdrag
      - familie-ba-dokgen
    environment:
      SPRING_PROFILES_ACTIVE: e2e
      BA_SAK_CLIENT_ID: ${SAK_CLIENT_ID}
      BA_MOTTAK_CLIENT_ID: ${MOTTAK_CLIENT_ID}
      BA_SAK_FRONTEND_CLIENT_ID: ${SAK_FRONTEND_CLIENT_ID}
      CLIENT_SECRET: ${SAK_CLIENT_SECRET}
      FAMILIE_INTEGRASJONER_SCOPE: ${INTEGRASJONER_SCOPE}
      FAMILIE_OPPDRAG_SCOPE: ${OPPDRAG_SCOPE}
    ports:
      - 8089:8089
  familie-redis:
    restart: always
    image: redis
    ports:
      - 6379:6379
  familie-ba-sak-frontend:
    restart: always
    depends_on:
      - mock-oauth2-server
      - familie-ba-sak
      - familie-redis
    image: docker.pkg.github.com/navikt/familie-ba-sak-frontend/familie-ba-sak-frontend:latest
    ports:
      - 8000:8000
    environment:
      ENV: e2e
      SESSION_SECRET: ${SESSION_SECRET}
      CLIENT_ID: ${SAK_FRONTEND_CLIENT_ID}
      CLIENT_SECRET: ${SAK_FRONTEND_CLIENT_SECRET}
      BA_SAK_SCOPE: ${BA_SAK_SCOPE}
      PASSPORTCOOKIE_KEY1: KEY1
      PASSPORTCOOKIE_KEY2: KEY2
      PASSPORTCOOKIE_KEY3: KEY3
      PASSPORTCOOKIE_KEY4: KEY4
      COOKIE_KEY1: COOKIE_KEY1
      COOKIE_KEY2: COOKIE_KEY1
      SLACK_TOKEN: SLACK_TOKEN
  familie-integrasjoner:
    restart: always
    image: docker.pkg.github.com/navikt/familie-integrasjoner/familie-integrasjoner:latest
    depends_on:
      - familie-mock-server
      - mock-oauth2-server
    volumes:
      - ./modig:/root/.modig
    environment:
      SPRING_PROFILES_ACTIVE: e2e
      INTEGRASJONER_CLIENT_ID: ${INTEGRASJONER_CLIENT_ID}
      INTEGRASJONER_CLIENT_SECRET: ${INTEGRASJONER_CLIENT_SECRET}
      INFOTRYGD_KS_SCOPE: ${INTEGRASJONER_INFOTRYGD_KS_SCOPE}
      AAD_GRAPH_SCOPE: ${INTEGRASJONER_AAD_GRAPH_SCOPE}
    ports:
      - 8085:8085
  familie-oppdrag:
    restart: always
    image: docker.pkg.github.com/navikt/familie-oppdrag/familie-oppdrag:latest
    depends_on:
      - mq
      - mock-oauth2-server
      - postgres-oppdrag
    environment:
      SPRING_PROFILES_ACTIVE: e2e
      OPPDRAG_CLIENT_ID: ${OPPDRAG_CLIENT_ID}
      OPPDRAG_BA_SAK_CLIENT_ID: ${SAK_CLIENT_ID}
    ports:
      - 8087:8087
  familie-ba-dokgen:
    restart: always
    image: docker.pkg.github.com/navikt/familie-ba-dokgen/familie-ba-dokgen:latest
    ports:
      - 8091:8080
