version: "3"
services:
  openldap:
    build: ldap
    container_name: ldap
    ports:
      - "10636:636"
      - "10389:389"
    environment:
      - "LDAP_TLS_VERIFY_CLIENT=try"
  zookeeper:
    #image: confluentinc/cp-zookeeper
    build: zookeeper
    container_name: zookeeper
    environment:
      - "ZOOKEEPER_CLIENT_PORT=2181"
      - "ZOOKEEPER_AUTH_PROVIDER_1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider"
    ports:
      - "2181:2181"
  kafka:
    build: kafka
    container_name: kafka
    environment:
      - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
      - "KAFKA_LISTENERS=SASLPLAINTEXT://0.0.0.0:9092,SASLINTERNAL://kafka:9093"
      - "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=SASLPLAINTEXT:SASL_PLAINTEXT,SASLINTERNAL:SASL_PLAINTEXT"
      - "KAFKA_ADVERTISED_LISTENERS=SASLPLAINTEXT://localhost:9092,SASLINTERNAL://kafka:9093"
      - "KAFKA_PROTOCOL_NAME=SASLPLAINTEXT,SASLINTERNAL"
      - "KAFKA_LISTENER_NAME_SASLPLAINTEXT_PLAIN_SASL_SERVER_CALLBACK_HANDLER_CLASS=no.nav.common.security.authentication.SimpleLDAPAuthentication"
      - "KAFKA_LISTENER_NAME_SASLINTERNAL_PLAIN_SASL_SERVER_CALLBACK_HANDLER_CLASS=no.nav.common.security.authentication.SimpleLDAPAuthentication"
      - "KAFKA_AUTHORIZER_CLASS_NAME=no.nav.common.security.authorization.SimpleLDAPAuthorizer"
      - "KAFKA_SUPER_USERS=User:igroup"
      - "KAFKA_INTER_BROKER_LISTENER_NAME=SASLINTERNAL"
      - "KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN"
      - "KAFKA_SASL_ENABLED_MECHANISMS=PLAIN"
      - "KAFKA_DEFAULT_REPLICATION_FACTOR=1"
      - "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1"
      - "KAFKA_AUTO_CREATE_TOPICS_ENABLE=true"
      - "KAFKA_CREATE_TOPICS=aapen-person-pdl-leesah-v1:1:1,aapen-dok-journalfoering-v1-e2e:1:1"
    ports:
      - "9092:9092"
    depends_on:
      - "zookeeper"
      - "openldap"
  kafkadminrest:
    image: "navikt/kafka-adminrest"
    ports:
      - "8840:8080"
    environment:
      - "LDAP_CONNTIMEOUT=2000"
      - "LDAP_USERATTRNAME=cn"
      - "LDAP_AUTH_HOST=ldap"
      - "LDAP_AUTH_PORT=636"
      - "LDAP_SRVUSERBASE=OU=ServiceAccounts,DC=test,DC=local"
      - "LDAP_GROUPBASE=OU=kafka,OU=AccountGroupNotInRemedy,OU=Groups,OU=NAV,OU=BusinessUnits,DC=test,DC=local"
      - "LDAP_GROUPATTRNAME=cn"
      - "LDAP_GRPMEMBERATTRNAME=member"
      - "LDAP_USER=igroup"
      - "LDAP_PASSWORD=itest"
      - "KAFKA_BROKERS=kafka:9093"
      - "KAFKA_CLIENTID=kafka-adminrest"
      - "KAFKA_SECURITY=TRUE"
      - "KAFKA_SECPROT=SASL_PLAINTEXT"
      - "KAFKA_SASLMEC=PLAIN"
      - "KAFKA_USER=igroup"
      - "LDAP_HOST=ldap"
      - "LDAP_PORT=636"
      - "LDAP_AUTH_USERBASE=ou=Users,ou=NAV,dc=test,dc=local"
      - "KAFKA_PASSWORD=itest"
  schema-registry:
    image: "confluentinc/cp-schema-registry:5.0.1"
    depends_on:
      - "zookeeper"
      - "kafka"
    ports:
      - "8081:8081"
    environment:
      - "SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=SASL_PLAINTEXT://kafka:9093"
      - "SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM=PLAIN"
      - 'SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="igroup" password="itest";'
      - "SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL=SASL_PLAINTEXT"
      - "SCHEMA_REGISTRY_HOST_NAME=schema-registry"
      - "SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081"
  vtp:
    image: docker.pkg.github.com/navikt/vtp/vtp:latest
    environment:
      ISSO_OAUTH2_ISSUER: azuread
    volumes:
      - ./modig:/root/.modig
    ports:
      - 8060:8060
      - 8063:8063
  familie-mock-server:
    image: docker.pkg.github.com/navikt/familie-mock-server
    ports:
      - 1337:1337
  mock-oauth2-server:
    image: docker.pkg.github.com/navikt/mock-oauth2-server/mock-oauth2-server:0.1.33
    ports:
      - 1111:1111
    hostname: host.docker.internal
  nav-auth-mock:
    image: docker.pkg.github.com/navikt/nav-auth-mock/nav-auth-mock
    ports:
      - 8200:8200
  postgres-sak:
    image: postgres:11
    environment:
      POSTGRES_USER: familie
      POSTGRES_DB: familiebasak
      POSTGRES_PASSWORD: familie-pwd
    ports:
      - 5432:5432
  postgres-mottak:
    image: postgres:11
    environment:
      POSTGRES_USER: familie
      POSTGRES_DB: familiebamottak
      POSTGRES_PASSWORD: familie-pwd
    ports:
      - 5439:5432
  familie-ba-mottak:
    restart: always
    depends_on:
      - kafka
    image: docker.pkg.github.com/navikt/familie-ba-mottak/familie-ba-mottak:latest
    environment:
      SPRING_PROFILES_ACTIVE: e2e
      MOTTAK_CLIENT_ID: ${MOTTAK_CLIENT_ID}
      MOTTAK_FRONTEND_CLIENT_ID: ${MOTTAK_FRONTEND_CLIENT_ID}
      MOTTAK_CLIENT_SECRET: ${MOTTAK_CLIENT_SECRET}
      MOTTAK_BA_SAK_SCOPE: ${BA_SAK_SCOPE}
      MOTTAK_FAMILIE_INTEGRASJONER_SCOPE: ${INTEGRASJONER_SCOPE}
      JOURNALFOERINGHENDELSE_V1_TOPIC_URL: aapen-dok-journalfoering-v1-e2e
  familie-ba-sak:
    restart: always
    image: docker.pkg.github.com/navikt/familie-ba-sak/familie-ba-sak:latest
    depends_on:
      - familie-integrasjoner
    environment:
      SPRING_PROFILES_ACTIVE: e2e
      BA_SAK_CLIENT_ID: ${SAK_CLIENT_ID}
      BA_MOTTAK_CLIENT_ID: ${MOTTAK_CLIENT_ID}
      BA_SAK_FRONTEND_CLIENT_ID: ${SAK_FRONTEND_CLIENT_ID}
      CLIENT_SECRET: ${SAK_CLIENT_SECRET}
      FAMILIE_INTEGRASJONER_SCOPE: ${INTEGRASJONER_SCOPE}
      FAMILIE_OPPDRAG_SCOPE: ${OPPDRAG_SCOPE}
    ports:
      - 8089:8089
  familie-redis:
    restart: always
    image: redis
    ports:
      - 6379:6379
  familie-ba-sak-frontend:
    restart: always
    depends_on:
      - mock-oauth2-server
      - familie-ba-sak
      - familie-redis
    image: navikt/familie-ba-sak-frontend:0.0.1-0ff6f0091e0eedac84ffd84e4c2b1ceefa01b79f
    ports:
      - 8000:8000
    environment:
      ENV: e2e
      SESSION_SECRET: ${SESSION_SECRET}
      CLIENT_ID: ${SAK_FRONTEND_CLIENT_ID}
      CLIENT_SECRET: ${SAK_FRONTEND_CLIENT_SECRET}
      BA_SAK_SCOPE: ${BA_SAK_SCOPE}
      PASSPORTCOOKIE_KEY1: KEY1
      PASSPORTCOOKIE_KEY2: KEY2
      PASSPORTCOOKIE_KEY3: KEY3
      PASSPORTCOOKIE_KEY4: KEY4
      COOKIE_KEY1: COOKIE_KEY1
      COOKIE_KEY2: COOKIE_KEY1
      SLACK_TOKEN: SLACK_TOKEN
  familie-integrasjoner:
    restart: always
    image: docker.pkg.github.com/navikt/familie-integrasjoner/familie-integrasjoner:latest
    depends_on:
      - familie-mock-server
    volumes:
      - ./modig:/root/.modig
    environment:
      SPRING_PROFILES_ACTIVE: e2e
      INTEGRASJONER_CLIENT_ID: ${INTEGRASJONER_CLIENT_ID}
      INTEGRASJONER_CLIENT_SECRET: ${INTEGRASJONER_CLIENT_SECRET}
      INFOTRYGD_KS_SCOPE: ${INTEGRASJONER_INFOTRYGD_KS_SCOPE}
      AAD_GRAPH_SCOPE: ${INTEGRASJONER_AAD_GRAPH_SCOPE}
    ports:
      - 8085:8085
