FROM docker.pkg.github.com/navikt/familie-ba-sak-frontend/familie-ba-sak-frontend:e04cf94fc9b44494f5bcc686827a5581da6ee89f

RUN echo "Fra dockercontainer"
RUN hostname
RUN ping -c4 host.docker.internal