version: '3.2'

services:
  vtp:
    image: docker.pkg.github.com/navikt/vtp/vtp:latest
    environment:
      ISSO_OAUTH2_ISSUER: azuread
    volumes:
      - ./modig:/root/.modig
    ports:
      - 8060:8060
  familie-oidc-test:
    image: docker.pkg.github.com/navikt/familie-oidc-test/familie-oidc-test:2019.11.05-04e374d
    ports:
      - 10001:8080
    environment:
      SPRING_PROFILES_ACTIVE: e2e
  localstack:
    image: localstack/localstack
    ports:
      - 10000:10000
    environment:
      - SERVICES=s3,sts
  postgres-sak:
    image: postgres:11
    environment:
      POSTGRES_USER: familie
      POSTGRES_DB: familiebasak
      POSTGRES_PASSWORD: familie-pwd
    ports:
      - 5432:5432
  postgres-mottak:
    image: postgres:11
    environment:
      POSTGRES_USER: familie
      POSTGRES_DB: familiebamottak
      POSTGRES_PASSWORD: familie-pwd
